- name: install and run nginx
  hosts: web
  become: yes #then it will become root access
  tasks:
   - name: install nginx package
     ansible.builtin.package:
      name: chrony
      state: present
   - name: run nginx
     ansible.builtin.service:
      name: nginx
      state: started

