- name: variables from prompt
  hosts: localhosts
  vars_prompt:
  - name: username
    prompt: Please enter your username
    private: false # user can see what they are entering
  - name: Password
    prompt: please enter your Password
    private: true #user cant see what they are entering  
  tasks:
  - name: print and check the values
    ansible.builtin.debug:
     msg: "username is: {{USERNAME}}, Password is: {{PASSWORD}}"
   
